-- Current sql file was generated after introspecting the database
-- If you want to run this migration please uncomment this code before executing migrations
/*
CREATE TABLE `groups` (
	`id` integer PRIMARY KEY AUTOINCREMENT,
	`name` text NOT NULL,
	`description` text,
	`leader_id` integer NOT NULL,
	`created_at` text DEFAULT (datetime('now')) NOT NULL,
	CONSTRAINT "users_check_1" CHECK(role IN ('joven','lider','admin'),
	CONSTRAINT "plan_assignments_check_2" CHECK(assigned_to IN ('all','group','individual'),
	CONSTRAINT "reading_progress_check_3" CHECK(status IN ('available','completed','late','locked'),
	CONSTRAINT "devotionals_check_4" CHECK(status IN ('draft','submitted','reviewed'),
	CONSTRAINT "devotional_reactions_check_5" CHECK(type IN ('like','fire','heart','pray'),
	CONSTRAINT "tasks_check_6" CHECK(assigned_to IN ('all','group','individual'),
	CONSTRAINT "tasks_check_7" CHECK(evidence_type IN ('none','text','media','file'),
	CONSTRAINT "task_submissions_check_8" CHECK(status IN ('pending','submitted','approved','rejected'),
	CONSTRAINT "xp_log_check_9" CHECK(source_type IN ('reading','devotional','task','badge','manual','reversal'),
	CONSTRAINT "badges_check_10" CHECK(trigger_type IN ('auto','manual'),
	CONSTRAINT "prayer_requests_check_11" CHECK(status IN ('praying','answered'),
	CONSTRAINT "event_attendance_check_12" CHECK(status IN ('confirmed','attended','absent')
);
--> statement-breakpoint
CREATE TABLE `users` (
	`id` integer PRIMARY KEY AUTOINCREMENT,
	`name` text NOT NULL,
	`email` text,
	`matricula` text,
	`password_hash` text NOT NULL,
	`role` text DEFAULT 'joven' NOT NULL,
	`avatar` text,
	`group_id` integer,
	`xp` integer DEFAULT 0 NOT NULL,
	`level` integer DEFAULT 1 NOT NULL,
	`streak_current` integer DEFAULT 0 NOT NULL,
	`streak_best` integer DEFAULT 0 NOT NULL,
	`last_read_date` text,
	`share_devotionals` integer DEFAULT 0 NOT NULL,
	`is_active` integer DEFAULT 1 NOT NULL,
	`joined_at` text DEFAULT (datetime('now')) NOT NULL,
	`created_at` text DEFAULT (datetime('now')) NOT NULL,
	`updated_at` text DEFAULT (datetime('now')) NOT NULL,
	FOREIGN KEY (`group_id`) REFERENCES `groups`(`id`) ON UPDATE no action ON DELETE no action,
	CONSTRAINT "users_check_1" CHECK(role IN ('joven','lider','admin'),
	CONSTRAINT "plan_assignments_check_2" CHECK(assigned_to IN ('all','group','individual'),
	CONSTRAINT "reading_progress_check_3" CHECK(status IN ('available','completed','late','locked'),
	CONSTRAINT "devotionals_check_4" CHECK(status IN ('draft','submitted','reviewed'),
	CONSTRAINT "devotional_reactions_check_5" CHECK(type IN ('like','fire','heart','pray'),
	CONSTRAINT "tasks_check_6" CHECK(assigned_to IN ('all','group','individual'),
	CONSTRAINT "tasks_check_7" CHECK(evidence_type IN ('none','text','media','file'),
	CONSTRAINT "task_submissions_check_8" CHECK(status IN ('pending','submitted','approved','rejected'),
	CONSTRAINT "xp_log_check_9" CHECK(source_type IN ('reading','devotional','task','badge','manual','reversal'),
	CONSTRAINT "badges_check_10" CHECK(trigger_type IN ('auto','manual'),
	CONSTRAINT "prayer_requests_check_11" CHECK(status IN ('praying','answered'),
	CONSTRAINT "event_attendance_check_12" CHECK(status IN ('confirmed','attended','absent')
);
--> statement-breakpoint
CREATE TABLE `reading_plans` (
	`id` integer PRIMARY KEY AUTOINCREMENT,
	`title` text NOT NULL,
	`description` text,
	`total_days` integer DEFAULT 0 NOT NULL,
	`created_by` integer NOT NULL,
	`is_active` integer DEFAULT 1 NOT NULL,
	`created_at` text DEFAULT (datetime('now')) NOT NULL,
	FOREIGN KEY (`created_by`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE no action,
	CONSTRAINT "users_check_1" CHECK(role IN ('joven','lider','admin'),
	CONSTRAINT "plan_assignments_check_2" CHECK(assigned_to IN ('all','group','individual'),
	CONSTRAINT "reading_progress_check_3" CHECK(status IN ('available','completed','late','locked'),
	CONSTRAINT "devotionals_check_4" CHECK(status IN ('draft','submitted','reviewed'),
	CONSTRAINT "devotional_reactions_check_5" CHECK(type IN ('like','fire','heart','pray'),
	CONSTRAINT "tasks_check_6" CHECK(assigned_to IN ('all','group','individual'),
	CONSTRAINT "tasks_check_7" CHECK(evidence_type IN ('none','text','media','file'),
	CONSTRAINT "task_submissions_check_8" CHECK(status IN ('pending','submitted','approved','rejected'),
	CONSTRAINT "xp_log_check_9" CHECK(source_type IN ('reading','devotional','task','badge','manual','reversal'),
	CONSTRAINT "badges_check_10" CHECK(trigger_type IN ('auto','manual'),
	CONSTRAINT "prayer_requests_check_11" CHECK(status IN ('praying','answered'),
	CONSTRAINT "event_attendance_check_12" CHECK(status IN ('confirmed','attended','absent')
);
--> statement-breakpoint
CREATE TABLE `reading_plan_days` (
	`id` integer PRIMARY KEY AUTOINCREMENT,
	`plan_id` integer NOT NULL,
	`day_number` integer NOT NULL,
	`title` text,
	`bible_refs` text NOT NULL,
	`xp_reward` integer DEFAULT 10 NOT NULL,
	FOREIGN KEY (`plan_id`) REFERENCES `reading_plans`(`id`) ON UPDATE no action ON DELETE no action,
	CONSTRAINT "users_check_1" CHECK(role IN ('joven','lider','admin'),
	CONSTRAINT "plan_assignments_check_2" CHECK(assigned_to IN ('all','group','individual'),
	CONSTRAINT "reading_progress_check_3" CHECK(status IN ('available','completed','late','locked'),
	CONSTRAINT "devotionals_check_4" CHECK(status IN ('draft','submitted','reviewed'),
	CONSTRAINT "devotional_reactions_check_5" CHECK(type IN ('like','fire','heart','pray'),
	CONSTRAINT "tasks_check_6" CHECK(assigned_to IN ('all','group','individual'),
	CONSTRAINT "tasks_check_7" CHECK(evidence_type IN ('none','text','media','file'),
	CONSTRAINT "task_submissions_check_8" CHECK(status IN ('pending','submitted','approved','rejected'),
	CONSTRAINT "xp_log_check_9" CHECK(source_type IN ('reading','devotional','task','badge','manual','reversal'),
	CONSTRAINT "badges_check_10" CHECK(trigger_type IN ('auto','manual'),
	CONSTRAINT "prayer_requests_check_11" CHECK(status IN ('praying','answered'),
	CONSTRAINT "event_attendance_check_12" CHECK(status IN ('confirmed','attended','absent')
);
--> statement-breakpoint
CREATE TABLE `plan_assignments` (
	`id` integer PRIMARY KEY AUTOINCREMENT,
	`plan_id` integer NOT NULL,
	`assigned_to` text NOT NULL,
	`group_id` integer,
	`user_id` integer,
	`start_date` text NOT NULL,
	`created_at` text DEFAULT (datetime('now')) NOT NULL,
	FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`group_id`) REFERENCES `groups`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`plan_id`) REFERENCES `reading_plans`(`id`) ON UPDATE no action ON DELETE no action,
	CONSTRAINT "users_check_1" CHECK(role IN ('joven','lider','admin'),
	CONSTRAINT "plan_assignments_check_2" CHECK(assigned_to IN ('all','group','individual'),
	CONSTRAINT "reading_progress_check_3" CHECK(status IN ('available','completed','late','locked'),
	CONSTRAINT "devotionals_check_4" CHECK(status IN ('draft','submitted','reviewed'),
	CONSTRAINT "devotional_reactions_check_5" CHECK(type IN ('like','fire','heart','pray'),
	CONSTRAINT "tasks_check_6" CHECK(assigned_to IN ('all','group','individual'),
	CONSTRAINT "tasks_check_7" CHECK(evidence_type IN ('none','text','media','file'),
	CONSTRAINT "task_submissions_check_8" CHECK(status IN ('pending','submitted','approved','rejected'),
	CONSTRAINT "xp_log_check_9" CHECK(source_type IN ('reading','devotional','task','badge','manual','reversal'),
	CONSTRAINT "badges_check_10" CHECK(trigger_type IN ('auto','manual'),
	CONSTRAINT "prayer_requests_check_11" CHECK(status IN ('praying','answered'),
	CONSTRAINT "event_attendance_check_12" CHECK(status IN ('confirmed','attended','absent')
);
--> statement-breakpoint
CREATE TABLE `reading_progress` (
	`id` integer PRIMARY KEY AUTOINCREMENT,
	`user_id` integer NOT NULL,
	`plan_id` integer NOT NULL,
	`plan_day_id` integer NOT NULL,
	`status` text DEFAULT 'locked' NOT NULL,
	`completed_at` text,
	`is_catch_up` integer DEFAULT 0 NOT NULL,
	FOREIGN KEY (`plan_day_id`) REFERENCES `reading_plan_days`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`plan_id`) REFERENCES `reading_plans`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE no action,
	CONSTRAINT "users_check_1" CHECK(role IN ('joven','lider','admin'),
	CONSTRAINT "plan_assignments_check_2" CHECK(assigned_to IN ('all','group','individual'),
	CONSTRAINT "reading_progress_check_3" CHECK(status IN ('available','completed','late','locked'),
	CONSTRAINT "devotionals_check_4" CHECK(status IN ('draft','submitted','reviewed'),
	CONSTRAINT "devotional_reactions_check_5" CHECK(type IN ('like','fire','heart','pray'),
	CONSTRAINT "tasks_check_6" CHECK(assigned_to IN ('all','group','individual'),
	CONSTRAINT "tasks_check_7" CHECK(evidence_type IN ('none','text','media','file'),
	CONSTRAINT "task_submissions_check_8" CHECK(status IN ('pending','submitted','approved','rejected'),
	CONSTRAINT "xp_log_check_9" CHECK(source_type IN ('reading','devotional','task','badge','manual','reversal'),
	CONSTRAINT "badges_check_10" CHECK(trigger_type IN ('auto','manual'),
	CONSTRAINT "prayer_requests_check_11" CHECK(status IN ('praying','answered'),
	CONSTRAINT "event_attendance_check_12" CHECK(status IN ('confirmed','attended','absent')
);
--> statement-breakpoint
CREATE TABLE `devotionals` (
	`id` integer PRIMARY KEY AUTOINCREMENT,
	`user_id` integer NOT NULL,
	`plan_day_id` integer NOT NULL,
	`what_i_read` text NOT NULL,
	`what_i_understood` text NOT NULL,
	`what_god_told_me` text NOT NULL,
	`what_i_practice` text NOT NULL,
	`status` text DEFAULT 'draft' NOT NULL,
	`is_public` integer DEFAULT 0 NOT NULL,
	`created_at` text DEFAULT (datetime('now')) NOT NULL,
	`updated_at` text DEFAULT (datetime('now')) NOT NULL,
	FOREIGN KEY (`plan_day_id`) REFERENCES `reading_plan_days`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE no action,
	CONSTRAINT "users_check_1" CHECK(role IN ('joven','lider','admin'),
	CONSTRAINT "plan_assignments_check_2" CHECK(assigned_to IN ('all','group','individual'),
	CONSTRAINT "reading_progress_check_3" CHECK(status IN ('available','completed','late','locked'),
	CONSTRAINT "devotionals_check_4" CHECK(status IN ('draft','submitted','reviewed'),
	CONSTRAINT "devotional_reactions_check_5" CHECK(type IN ('like','fire','heart','pray'),
	CONSTRAINT "tasks_check_6" CHECK(assigned_to IN ('all','group','individual'),
	CONSTRAINT "tasks_check_7" CHECK(evidence_type IN ('none','text','media','file'),
	CONSTRAINT "task_submissions_check_8" CHECK(status IN ('pending','submitted','approved','rejected'),
	CONSTRAINT "xp_log_check_9" CHECK(source_type IN ('reading','devotional','task','badge','manual','reversal'),
	CONSTRAINT "badges_check_10" CHECK(trigger_type IN ('auto','manual'),
	CONSTRAINT "prayer_requests_check_11" CHECK(status IN ('praying','answered'),
	CONSTRAINT "event_attendance_check_12" CHECK(status IN ('confirmed','attended','absent')
);
--> statement-breakpoint
CREATE TABLE `devotional_reactions` (
	`id` integer PRIMARY KEY AUTOINCREMENT,
	`devotional_id` integer NOT NULL,
	`user_id` integer NOT NULL,
	`type` text NOT NULL,
	`comment` text,
	`created_at` text DEFAULT (datetime('now')) NOT NULL,
	FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`devotional_id`) REFERENCES `devotionals`(`id`) ON UPDATE no action ON DELETE no action,
	CONSTRAINT "users_check_1" CHECK(role IN ('joven','lider','admin'),
	CONSTRAINT "plan_assignments_check_2" CHECK(assigned_to IN ('all','group','individual'),
	CONSTRAINT "reading_progress_check_3" CHECK(status IN ('available','completed','late','locked'),
	CONSTRAINT "devotionals_check_4" CHECK(status IN ('draft','submitted','reviewed'),
	CONSTRAINT "devotional_reactions_check_5" CHECK(type IN ('like','fire','heart','pray'),
	CONSTRAINT "tasks_check_6" CHECK(assigned_to IN ('all','group','individual'),
	CONSTRAINT "tasks_check_7" CHECK(evidence_type IN ('none','text','media','file'),
	CONSTRAINT "task_submissions_check_8" CHECK(status IN ('pending','submitted','approved','rejected'),
	CONSTRAINT "xp_log_check_9" CHECK(source_type IN ('reading','devotional','task','badge','manual','reversal'),
	CONSTRAINT "badges_check_10" CHECK(trigger_type IN ('auto','manual'),
	CONSTRAINT "prayer_requests_check_11" CHECK(status IN ('praying','answered'),
	CONSTRAINT "event_attendance_check_12" CHECK(status IN ('confirmed','attended','absent')
);
--> statement-breakpoint
CREATE TABLE `tasks` (
	`id` integer PRIMARY KEY AUTOINCREMENT,
	`title` text NOT NULL,
	`description` text,
	`assigned_to` text NOT NULL,
	`group_id` integer,
	`user_id` integer,
	`evidence_type` text DEFAULT 'none' NOT NULL,
	`xp_reward` integer DEFAULT 20 NOT NULL,
	`deadline` text,
	`created_by` integer NOT NULL,
	`is_active` integer DEFAULT 1 NOT NULL,
	`created_at` text DEFAULT (datetime('now')) NOT NULL,
	FOREIGN KEY (`created_by`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`group_id`) REFERENCES `groups`(`id`) ON UPDATE no action ON DELETE no action,
	CONSTRAINT "users_check_1" CHECK(role IN ('joven','lider','admin'),
	CONSTRAINT "plan_assignments_check_2" CHECK(assigned_to IN ('all','group','individual'),
	CONSTRAINT "reading_progress_check_3" CHECK(status IN ('available','completed','late','locked'),
	CONSTRAINT "devotionals_check_4" CHECK(status IN ('draft','submitted','reviewed'),
	CONSTRAINT "devotional_reactions_check_5" CHECK(type IN ('like','fire','heart','pray'),
	CONSTRAINT "tasks_check_6" CHECK(assigned_to IN ('all','group','individual'),
	CONSTRAINT "tasks_check_7" CHECK(evidence_type IN ('none','text','media','file'),
	CONSTRAINT "task_submissions_check_8" CHECK(status IN ('pending','submitted','approved','rejected'),
	CONSTRAINT "xp_log_check_9" CHECK(source_type IN ('reading','devotional','task','badge','manual','reversal'),
	CONSTRAINT "badges_check_10" CHECK(trigger_type IN ('auto','manual'),
	CONSTRAINT "prayer_requests_check_11" CHECK(status IN ('praying','answered'),
	CONSTRAINT "event_attendance_check_12" CHECK(status IN ('confirmed','attended','absent')
);
--> statement-breakpoint
CREATE TABLE `task_submissions` (
	`id` integer PRIMARY KEY AUTOINCREMENT,
	`task_id` integer NOT NULL,
	`user_id` integer NOT NULL,
	`evidence` text,
	`status` text DEFAULT 'pending' NOT NULL,
	`review_note` text,
	`reviewed_by` integer,
	`reviewed_at` text,
	`submitted_at` text DEFAULT (datetime('now')) NOT NULL,
	FOREIGN KEY (`reviewed_by`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`task_id`) REFERENCES `tasks`(`id`) ON UPDATE no action ON DELETE no action,
	CONSTRAINT "users_check_1" CHECK(role IN ('joven','lider','admin'),
	CONSTRAINT "plan_assignments_check_2" CHECK(assigned_to IN ('all','group','individual'),
	CONSTRAINT "reading_progress_check_3" CHECK(status IN ('available','completed','late','locked'),
	CONSTRAINT "devotionals_check_4" CHECK(status IN ('draft','submitted','reviewed'),
	CONSTRAINT "devotional_reactions_check_5" CHECK(type IN ('like','fire','heart','pray'),
	CONSTRAINT "tasks_check_6" CHECK(assigned_to IN ('all','group','individual'),
	CONSTRAINT "tasks_check_7" CHECK(evidence_type IN ('none','text','media','file'),
	CONSTRAINT "task_submissions_check_8" CHECK(status IN ('pending','submitted','approved','rejected'),
	CONSTRAINT "xp_log_check_9" CHECK(source_type IN ('reading','devotional','task','badge','manual','reversal'),
	CONSTRAINT "badges_check_10" CHECK(trigger_type IN ('auto','manual'),
	CONSTRAINT "prayer_requests_check_11" CHECK(status IN ('praying','answered'),
	CONSTRAINT "event_attendance_check_12" CHECK(status IN ('confirmed','attended','absent')
);
--> statement-breakpoint
CREATE TABLE `xp_log` (
	`id` integer PRIMARY KEY AUTOINCREMENT,
	`user_id` integer NOT NULL,
	`amount` integer NOT NULL,
	`reason` text NOT NULL,
	`source_type` text NOT NULL,
	`source_id` integer,
	`granted_by` integer,
	`created_at` text DEFAULT (datetime('now')) NOT NULL,
	FOREIGN KEY (`granted_by`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE no action,
	CONSTRAINT "users_check_1" CHECK(role IN ('joven','lider','admin'),
	CONSTRAINT "plan_assignments_check_2" CHECK(assigned_to IN ('all','group','individual'),
	CONSTRAINT "reading_progress_check_3" CHECK(status IN ('available','completed','late','locked'),
	CONSTRAINT "devotionals_check_4" CHECK(status IN ('draft','submitted','reviewed'),
	CONSTRAINT "devotional_reactions_check_5" CHECK(type IN ('like','fire','heart','pray'),
	CONSTRAINT "tasks_check_6" CHECK(assigned_to IN ('all','group','individual'),
	CONSTRAINT "tasks_check_7" CHECK(evidence_type IN ('none','text','media','file'),
	CONSTRAINT "task_submissions_check_8" CHECK(status IN ('pending','submitted','approved','rejected'),
	CONSTRAINT "xp_log_check_9" CHECK(source_type IN ('reading','devotional','task','badge','manual','reversal'),
	CONSTRAINT "badges_check_10" CHECK(trigger_type IN ('auto','manual'),
	CONSTRAINT "prayer_requests_check_11" CHECK(status IN ('praying','answered'),
	CONSTRAINT "event_attendance_check_12" CHECK(status IN ('confirmed','attended','absent')
);
--> statement-breakpoint
CREATE TABLE `badges` (
	`id` integer PRIMARY KEY AUTOINCREMENT,
	`name` text NOT NULL,
	`description` text,
	`icon` text NOT NULL,
	`color` text DEFAULT '#C8F135' NOT NULL,
	`trigger_type` text DEFAULT 'manual' NOT NULL,
	`trigger_condition` text,
	`is_active` integer DEFAULT 1 NOT NULL,
	CONSTRAINT "users_check_1" CHECK(role IN ('joven','lider','admin'),
	CONSTRAINT "plan_assignments_check_2" CHECK(assigned_to IN ('all','group','individual'),
	CONSTRAINT "reading_progress_check_3" CHECK(status IN ('available','completed','late','locked'),
	CONSTRAINT "devotionals_check_4" CHECK(status IN ('draft','submitted','reviewed'),
	CONSTRAINT "devotional_reactions_check_5" CHECK(type IN ('like','fire','heart','pray'),
	CONSTRAINT "tasks_check_6" CHECK(assigned_to IN ('all','group','individual'),
	CONSTRAINT "tasks_check_7" CHECK(evidence_type IN ('none','text','media','file'),
	CONSTRAINT "task_submissions_check_8" CHECK(status IN ('pending','submitted','approved','rejected'),
	CONSTRAINT "xp_log_check_9" CHECK(source_type IN ('reading','devotional','task','badge','manual','reversal'),
	CONSTRAINT "badges_check_10" CHECK(trigger_type IN ('auto','manual'),
	CONSTRAINT "prayer_requests_check_11" CHECK(status IN ('praying','answered'),
	CONSTRAINT "event_attendance_check_12" CHECK(status IN ('confirmed','attended','absent')
);
--> statement-breakpoint
CREATE TABLE `user_badges` (
	`id` integer PRIMARY KEY AUTOINCREMENT,
	`user_id` integer NOT NULL,
	`badge_id` integer NOT NULL,
	`granted_by` integer,
	`granted_at` text DEFAULT (datetime('now')) NOT NULL,
	FOREIGN KEY (`granted_by`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`badge_id`) REFERENCES `badges`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE no action,
	CONSTRAINT "users_check_1" CHECK(role IN ('joven','lider','admin'),
	CONSTRAINT "plan_assignments_check_2" CHECK(assigned_to IN ('all','group','individual'),
	CONSTRAINT "reading_progress_check_3" CHECK(status IN ('available','completed','late','locked'),
	CONSTRAINT "devotionals_check_4" CHECK(status IN ('draft','submitted','reviewed'),
	CONSTRAINT "devotional_reactions_check_5" CHECK(type IN ('like','fire','heart','pray'),
	CONSTRAINT "tasks_check_6" CHECK(assigned_to IN ('all','group','individual'),
	CONSTRAINT "tasks_check_7" CHECK(evidence_type IN ('none','text','media','file'),
	CONSTRAINT "task_submissions_check_8" CHECK(status IN ('pending','submitted','approved','rejected'),
	CONSTRAINT "xp_log_check_9" CHECK(source_type IN ('reading','devotional','task','badge','manual','reversal'),
	CONSTRAINT "badges_check_10" CHECK(trigger_type IN ('auto','manual'),
	CONSTRAINT "prayer_requests_check_11" CHECK(status IN ('praying','answered'),
	CONSTRAINT "event_attendance_check_12" CHECK(status IN ('confirmed','attended','absent')
);
--> statement-breakpoint
CREATE TABLE `streak_history` (
	`id` integer PRIMARY KEY AUTOINCREMENT,
	`user_id` integer NOT NULL,
	`date` text NOT NULL,
	`completed` integer DEFAULT 0 NOT NULL,
	`is_catch_up` integer DEFAULT 0 NOT NULL,
	FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE no action,
	CONSTRAINT "users_check_1" CHECK(role IN ('joven','lider','admin'),
	CONSTRAINT "plan_assignments_check_2" CHECK(assigned_to IN ('all','group','individual'),
	CONSTRAINT "reading_progress_check_3" CHECK(status IN ('available','completed','late','locked'),
	CONSTRAINT "devotionals_check_4" CHECK(status IN ('draft','submitted','reviewed'),
	CONSTRAINT "devotional_reactions_check_5" CHECK(type IN ('like','fire','heart','pray'),
	CONSTRAINT "tasks_check_6" CHECK(assigned_to IN ('all','group','individual'),
	CONSTRAINT "tasks_check_7" CHECK(evidence_type IN ('none','text','media','file'),
	CONSTRAINT "task_submissions_check_8" CHECK(status IN ('pending','submitted','approved','rejected'),
	CONSTRAINT "xp_log_check_9" CHECK(source_type IN ('reading','devotional','task','badge','manual','reversal'),
	CONSTRAINT "badges_check_10" CHECK(trigger_type IN ('auto','manual'),
	CONSTRAINT "prayer_requests_check_11" CHECK(status IN ('praying','answered'),
	CONSTRAINT "event_attendance_check_12" CHECK(status IN ('confirmed','attended','absent')
);
--> statement-breakpoint
CREATE TABLE `prayer_requests` (
	`id` integer PRIMARY KEY AUTOINCREMENT,
	`user_id` integer NOT NULL,
	`content` text NOT NULL,
	`is_public` integer DEFAULT 0 NOT NULL,
	`is_anonymous` integer DEFAULT 0 NOT NULL,
	`status` text DEFAULT 'praying' NOT NULL,
	`created_at` text DEFAULT (datetime('now')) NOT NULL,
	`answered_at` text,
	FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE no action,
	CONSTRAINT "users_check_1" CHECK(role IN ('joven','lider','admin'),
	CONSTRAINT "plan_assignments_check_2" CHECK(assigned_to IN ('all','group','individual'),
	CONSTRAINT "reading_progress_check_3" CHECK(status IN ('available','completed','late','locked'),
	CONSTRAINT "devotionals_check_4" CHECK(status IN ('draft','submitted','reviewed'),
	CONSTRAINT "devotional_reactions_check_5" CHECK(type IN ('like','fire','heart','pray'),
	CONSTRAINT "tasks_check_6" CHECK(assigned_to IN ('all','group','individual'),
	CONSTRAINT "tasks_check_7" CHECK(evidence_type IN ('none','text','media','file'),
	CONSTRAINT "task_submissions_check_8" CHECK(status IN ('pending','submitted','approved','rejected'),
	CONSTRAINT "xp_log_check_9" CHECK(source_type IN ('reading','devotional','task','badge','manual','reversal'),
	CONSTRAINT "badges_check_10" CHECK(trigger_type IN ('auto','manual'),
	CONSTRAINT "prayer_requests_check_11" CHECK(status IN ('praying','answered'),
	CONSTRAINT "event_attendance_check_12" CHECK(status IN ('confirmed','attended','absent')
);
--> statement-breakpoint
CREATE TABLE `events` (
	`id` integer PRIMARY KEY AUTOINCREMENT,
	`title` text NOT NULL,
	`description` text,
	`location` text,
	`start_at` text NOT NULL,
	`end_at` text,
	`is_recurring` integer DEFAULT 0 NOT NULL,
	`recurrence_rule` text,
	`created_by` integer NOT NULL,
	`created_at` text DEFAULT (datetime('now')) NOT NULL,
	FOREIGN KEY (`created_by`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE no action,
	CONSTRAINT "users_check_1" CHECK(role IN ('joven','lider','admin'),
	CONSTRAINT "plan_assignments_check_2" CHECK(assigned_to IN ('all','group','individual'),
	CONSTRAINT "reading_progress_check_3" CHECK(status IN ('available','completed','late','locked'),
	CONSTRAINT "devotionals_check_4" CHECK(status IN ('draft','submitted','reviewed'),
	CONSTRAINT "devotional_reactions_check_5" CHECK(type IN ('like','fire','heart','pray'),
	CONSTRAINT "tasks_check_6" CHECK(assigned_to IN ('all','group','individual'),
	CONSTRAINT "tasks_check_7" CHECK(evidence_type IN ('none','text','media','file'),
	CONSTRAINT "task_submissions_check_8" CHECK(status IN ('pending','submitted','approved','rejected'),
	CONSTRAINT "xp_log_check_9" CHECK(source_type IN ('reading','devotional','task','badge','manual','reversal'),
	CONSTRAINT "badges_check_10" CHECK(trigger_type IN ('auto','manual'),
	CONSTRAINT "prayer_requests_check_11" CHECK(status IN ('praying','answered'),
	CONSTRAINT "event_attendance_check_12" CHECK(status IN ('confirmed','attended','absent')
);
--> statement-breakpoint
CREATE TABLE `event_attendance` (
	`id` integer PRIMARY KEY AUTOINCREMENT,
	`event_id` integer NOT NULL,
	`user_id` integer NOT NULL,
	`status` text DEFAULT 'confirmed' NOT NULL,
	`confirmed_at` text DEFAULT (datetime('now')) NOT NULL,
	FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`event_id`) REFERENCES `events`(`id`) ON UPDATE no action ON DELETE no action,
	CONSTRAINT "users_check_1" CHECK(role IN ('joven','lider','admin'),
	CONSTRAINT "plan_assignments_check_2" CHECK(assigned_to IN ('all','group','individual'),
	CONSTRAINT "reading_progress_check_3" CHECK(status IN ('available','completed','late','locked'),
	CONSTRAINT "devotionals_check_4" CHECK(status IN ('draft','submitted','reviewed'),
	CONSTRAINT "devotional_reactions_check_5" CHECK(type IN ('like','fire','heart','pray'),
	CONSTRAINT "tasks_check_6" CHECK(assigned_to IN ('all','group','individual'),
	CONSTRAINT "tasks_check_7" CHECK(evidence_type IN ('none','text','media','file'),
	CONSTRAINT "task_submissions_check_8" CHECK(status IN ('pending','submitted','approved','rejected'),
	CONSTRAINT "xp_log_check_9" CHECK(source_type IN ('reading','devotional','task','badge','manual','reversal'),
	CONSTRAINT "badges_check_10" CHECK(trigger_type IN ('auto','manual'),
	CONSTRAINT "prayer_requests_check_11" CHECK(status IN ('praying','answered'),
	CONSTRAINT "event_attendance_check_12" CHECK(status IN ('confirmed','attended','absent')
);
--> statement-breakpoint
CREATE TABLE `announcements` (
	`id` integer PRIMARY KEY AUTOINCREMENT,
	`title` text NOT NULL,
	`content` text NOT NULL,
	`author_id` integer NOT NULL,
	`is_pinned` integer DEFAULT 0 NOT NULL,
	`published_at` text DEFAULT (datetime('now')) NOT NULL,
	`expires_at` text,
	FOREIGN KEY (`author_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE no action,
	CONSTRAINT "users_check_1" CHECK(role IN ('joven','lider','admin'),
	CONSTRAINT "plan_assignments_check_2" CHECK(assigned_to IN ('all','group','individual'),
	CONSTRAINT "reading_progress_check_3" CHECK(status IN ('available','completed','late','locked'),
	CONSTRAINT "devotionals_check_4" CHECK(status IN ('draft','submitted','reviewed'),
	CONSTRAINT "devotional_reactions_check_5" CHECK(type IN ('like','fire','heart','pray'),
	CONSTRAINT "tasks_check_6" CHECK(assigned_to IN ('all','group','individual'),
	CONSTRAINT "tasks_check_7" CHECK(evidence_type IN ('none','text','media','file'),
	CONSTRAINT "task_submissions_check_8" CHECK(status IN ('pending','submitted','approved','rejected'),
	CONSTRAINT "xp_log_check_9" CHECK(source_type IN ('reading','devotional','task','badge','manual','reversal'),
	CONSTRAINT "badges_check_10" CHECK(trigger_type IN ('auto','manual'),
	CONSTRAINT "prayer_requests_check_11" CHECK(status IN ('praying','answered'),
	CONSTRAINT "event_attendance_check_12" CHECK(status IN ('confirmed','attended','absent')
);
--> statement-breakpoint
CREATE TABLE `notifications` (
	`id` integer PRIMARY KEY AUTOINCREMENT,
	`user_id` integer NOT NULL,
	`type` text NOT NULL,
	`title` text NOT NULL,
	`body` text,
	`is_read` integer DEFAULT 0 NOT NULL,
	`related_id` integer,
	`created_at` text DEFAULT (datetime('now')) NOT NULL,
	FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE no action,
	CONSTRAINT "users_check_1" CHECK(role IN ('joven','lider','admin'),
	CONSTRAINT "plan_assignments_check_2" CHECK(assigned_to IN ('all','group','individual'),
	CONSTRAINT "reading_progress_check_3" CHECK(status IN ('available','completed','late','locked'),
	CONSTRAINT "devotionals_check_4" CHECK(status IN ('draft','submitted','reviewed'),
	CONSTRAINT "devotional_reactions_check_5" CHECK(type IN ('like','fire','heart','pray'),
	CONSTRAINT "tasks_check_6" CHECK(assigned_to IN ('all','group','individual'),
	CONSTRAINT "tasks_check_7" CHECK(evidence_type IN ('none','text','media','file'),
	CONSTRAINT "task_submissions_check_8" CHECK(status IN ('pending','submitted','approved','rejected'),
	CONSTRAINT "xp_log_check_9" CHECK(source_type IN ('reading','devotional','task','badge','manual','reversal'),
	CONSTRAINT "badges_check_10" CHECK(trigger_type IN ('auto','manual'),
	CONSTRAINT "prayer_requests_check_11" CHECK(status IN ('praying','answered'),
	CONSTRAINT "event_attendance_check_12" CHECK(status IN ('confirmed','attended','absent')
);

*/